### ISSUE TITLE
Disabling surround mode

### ISSUE THREAD

**Issue by DrPyser** [alexherbo2/surround.kak#1]
Hi, thanks for this feature.

I'm having difficulty disabling surround mode. I'm using this in conjunction with [auto-pairs](https://github.com/alexherbo2/auto-pairs.kak). 

I activate the mode with `,s`, then I can enter insert mode and surround selections. When I escape insert mode, surround mode is not disabled.
 One consequence, is that whenever I create a pair at the end of a line, the closing pair character is inserted on the next line(surrounding the end line character).

Thanks!

**Comment by alexherbo2** [comment]
I’ll rework auto-pairs soon.  One thing you can do is disable auto-pairs when running surround and re-enable auto-pairs when leaving insert mode.

``` kak
define-command enter-surround-mode -params .. -docstring 'Enter surround mode' %{
  auto-pairs-disable
  surround %arg{@}
  hook -once window ModeChange 'pop:insert:.*' %{
    auto-pairs-enable
  }
}

map global user s ': enter-surround-mode<ret>' -docstring 'Enter surround mode'
map global user S ': enter-surround-mode _ _ * *<ret>' -docstring 'Enter surround mode with extra surrounding pairs'
```
