### ISSUE TITLE
surrounding surrounded text adds extra closing delimiter when auto-pairs mode is active

### ISSUE THREAD

**Issue by andreyorst** [alexherbo2/surround.kak#2]
Auto pairs enabled:
- in: (text)
- surround with `(`: `()(text))`
- expected outcome: `((text))`

Auto pairs disabled:
- in: (text)
- surround with `(`: `((text))`
- expected outcome: `((text))`

**Comment by alexherbo2** [comment]
``` kak
set-option global surround_begin auto-pairs-disable
set-option global surround_end auto-pairs-enable
```
