### ISSUE TITLE
Multi-character pairs

### ISSUE THREAD

**Issue by mreppen** [alexherbo2/surround.kak#3]
Great plugin!

The only thing missing for me is pairs of multiple characters. I edit a lot of LaTeX code, where `\[` `\]` `\big(` `\big)`, `\{` `\}`, and many other variations appear all over.

**Comment by alexherbo2** [comment]
How do you see that feature implemented?

**Comment by mreppen** [comment]
I am not sure what is reasonable in terms of actually implementing it, but this is how I imagine it would function: 

Say I start editing in surround on the left side of a selection. It would then "look at" what I enter and any occurrence of `\[` would be matched by `\]` on the right, while anything else is entered normally. At `\` nothing would happen, but when entering the `[`, `\]` would appear on the right.

**Comment by alexherbo2** [comment]
And how about HTML tags?

**Comment by alexherbo2** [comment]
@mreppen It is now possible.

``` kak
# Declare LaTeX mode
declare-user-mode surround-latex

# Expose LaTeX mode
map global surround -docstring 'Enter LaTeX mode' l ': enter-user-mode surround-latex<ret>'

# Surrounding pairs
map global surround-latex -docstring 'Big' b ": surround-add '\big(' '\big)'<ret>"

# Filetype-specific
hook global WinSetOption filetype=latex %{
  map window normal "<a-'>" ': enter-user-mode surround-latex<ret>'
}
```

**Comment by mreppen** [comment]
This looks really cool. Thanks!

I am mostly peer-reviewing these days, but I hope to test it out in real writing workflow soon

**Comment by alexherbo2** [comment]
I changed the suggested key-bindings from <kbd>'</kbd> to <kbd>q</kbd>.  I found the commands have to be really accessible to be useful.
