### ISSUE TITLE
Feature Request: replace surrounding pairs

### ISSUE THREAD

**Issue by basbebe** [alexherbo2/surround.kak#4]
I know I could `q<backslash>q"` if I wanted to change quotation style but maybe something like `<a-q>'"` would be more concise?

**Comment by alexherbo2** [comment]
How about:

```
Q<backspace>"
```

###### Configuration

``` kak
map -docstring 'Surround (lock)' global normal Q ': enter-user-mode -lock surround<ret>'
```

It replaces the mapping to enter in insert mode.

**Comment by basbebe** [comment]
but then it would be `Q<backspace>"<escape>`?

**Comment by alexherbo2** [comment]
Yep

**Comment by alexherbo2** [comment]
How about:

```
<a-q>"
```

###### Configuration

``` kak
map -docstring 'Surround (Replace)' global normal <a-q> ': surround-delete; enter-user-mode surround<ret>'
```

**Comment by basbebe** [comment]
that might work
